### ISSUE TITLE
Rate generator configuration

### ISSUE THREAD

**Issue by nivancevic** [smartcat-labs/berserker#14]
The following is one possible way to implement rate generator configuration.

1. Configuration is meant to be used in YAML conf file.
2. Using a util YAML class, the configuration would be relocatable, that is, an arbitrary configuration root could be used. A JasonPath could be used for selecting the configuration root (e.g. $.rate.generator[1].options).
3. There is a list of base rate generators:
        - impulse (interval, ratio)
        - sow-like (interval, ratio, tip ratio)
        - sine (interval)
        - random (interval, distribution)
        - limiter(cap, generator)
        - bell-shape (interval, median, variance)
        - circular-discrete (domain, interval)
        - exponential
        - logarithmic
4. All base generators have normalized output (0.0 .. 1.0).
5. The final/output rate is specified as an expression that combines outputs of base generators:
```
2000+1000*sin(interval)+50.0*random(interval2, uniform())
``` 
6. Syntax  for specifying time intervals should support expressions like: 2d30m (two days and 30 minutes), 5s (five seconds), 24h2m20s.
7. Configuration should provide a simplified syntax for simple cases.
8. Configuration should allow for specifying generator time offset. As all generators accept relative time (starting with 0), the time offset parameter can be used to translate generator function as needed.

Rate generator examples:

```
rate-gen-config:
  rate: 2000 + 1000*sin(6d30m)
```

```
rate-gen-config:
    offset: 24h
    rate:
      arate: 2000 + 1000*sin(2d2h50m10s500)
      brate: 5000*bell(7d, 2d) + 50*rnd(60s)
      output: 0.6*$arate + 0.3@brate
```
